defaults:
  - data: CP
  - model: CP-base
  - hardware: full
  - _self_

dataset_name: "PCDataset"
data_root: "data/frames/"
label_root: "data/labels/"
keypoints_root: "data/keypoints/"
venue_names:
- "2023-01-17-livingroom"


task: train
incl_all: false
train_ratio: 0.7
split_method: time
overfit: false
ckpt: null
noanswer: false

movie: null
lr: null
verbose: false
shrink_rate: 0.1
filter_joint: null # null, 'hand' or 'handhead'
use_preprocessed: false
debug: false
hist_error: false



